# Generated by ariadne-codegen on 2023-04-29 19:48
# Source: queries.graphql

from .async_base_client import AsyncBaseClient
from .gamer_tag import GamerTag
from .in_progress_results import InProgressResults
from .last_result import LastResult
from .upcoming import Upcoming


def gql(q: str) -> str:
    return q


class StartGGClient(AsyncBaseClient):
    async def gamer_tag(self, user_id: int) -> GamerTag:
        query = gql("""
            query GamerTag($userId: ID!) {
              user(id: $userId) {
                id
                slug
                player {
                  gamerTag
                }
              }
            }
            """)
        variables: dict[str, object] = {"userId": user_id}
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return GamerTag.parse_obj(data)

    async def last_result(
        self, user_id: int, per_page: int, gamer_tag: str
    ) -> LastResult:
        query = gql("""
            query LastResult($userId: ID!, $perPage: Int!, $gamerTag: String!) {
              user(id: $userId) {
                events(query: {perPage: $perPage, page: 1}) {
                  nodes {
                    tournament {
                      name
                      id
                      shortSlug
                    }
                    id
                    name
                    numEntrants
                    state
                    standings(
                      query: {perPage: $perPage, page: 1, filter: {search: {searchString: $gamerTag}}}
                    ) {
                      nodes {
                        entrant {
                          id
                        }
                        placement
                        isFinal
                      }
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "userId": user_id,
            "perPage": per_page,
            "gamerTag": gamer_tag,
        }
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return LastResult.parse_obj(data)

    async def upcoming(self, user_id: int, per_page: int, gamer_tag: str) -> Upcoming:
        query = gql("""
            query Upcoming($userId: ID!, $perPage: Int!, $gamerTag: String!) {
              user(id: $userId) {
                tournaments(query: {perPage: $perPage, page: 1, filter: {upcoming: true}}) {
                  nodes {
                    name
                    id
                    shortSlug
                    startAt
                    state
                    events(limit: 3) {
                      id
                      name
                      videogame {
                        id
                      }
                      entrants(query: {filter: {name: $gamerTag}}) {
                        nodes {
                          id
                        }
                      }
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "userId": user_id,
            "perPage": per_page,
            "gamerTag": gamer_tag,
        }
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return Upcoming.parse_obj(data)

    async def in_progress_results(
        self, event_id: int, entrant_id: int
    ) -> InProgressResults:
        query = gql("""
            query InProgressResults($event_id: ID!, $entrant_id: ID!) {
              event(id: $event_id) {
                tournament {
                  name
                }
                name
                sets(filters: {entrantIds: [$entrant_id]}) {
                  nodes {
                    fullRoundText
                    displayScore
                    wPlacement
                    lPlacement
                    winnerId
                    round
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"event_id": event_id, "entrant_id": entrant_id}
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return InProgressResults.parse_obj(data)
